DATASET_FINE: /home/emaraic/semanticSegmentation/datasets/cityscapes
DATASET_COARSE: /home/emaraic/semanticSegmentation/datasets/CityscapesExtra

USING_COARSE: False
BACKEND_NETWORK: MOBILENET

USING_GPU: TRUE
GPU_ID: 0

PRETRAINED_SHUFFLENET: /media/satya/740516b2-56c1-4cf3-9ae2-87b56289b807/work/project/segmentation/semantic-seg/network_evaluation/liteseg_model/pretrained_models/ShuffleNet_1g8_Top1_67.408_Top5_87.258.pth
PRETRAINED_MOBILENET: /media/satya/740516b2-56c1-4cf3-9ae2-87b56289b807/work/project/segmentation/semantic-seg/network_evaluation/liteseg_model/pretrained_models/mobilenet_v2.pth
PRETRAINED_DarkNET19: /media/satya/740516b2-56c1-4cf3-9ae2-87b56289b807/work/project/segmentation/semantic-seg/network_evaluation/liteseg_model/pretrained_models/darknet19_448.weights

